name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  java-maven-build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: echo "checkout code!!"
      - name: Build Java package
        run: |
          mkdir -p artifact
          cd java 
          mvn clean package -DskipTests=true -Dair.check.skip-duplicate-finder=True
          cp packages/Gluten-Trino-411.jar ../artifact/
      - uses: actions/upload-artifact@v3
        with: 
          name: java-artifact
          path: artifact/Gluten-Trino-411.jar
          path: artifact/Gluten-Trino-411-tests.jar

  build-cpp:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: build cpp
        run: |
          mkdir -p artifact
          cd cpp
          export TRINO_HOME=/trino_base
          git submodule update --init --recursive --force
          make release
          cp build-release/src/libgluten_trino.so ../artifact/
      - uses: actions/upload-artifact@v3
        with: 
          name: cpp-artifact
          path: artifact/libgluten_trino.so       

  cpp-code-style-check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: cpp code style check
        run: |
          scripts/check.py format branch
